# Generated by Django 5.0.4 on 2024-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Pendente", 1), ("Em Andamento", 2), ("Concluido", 3)],
                default=1,
                max_length=15,
                null=True,
            ),
        ),
    ]
